apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-mcp
  namespace: kagent
spec:
  replicas: 1
  selector:
    matchLabels: { app: postgres-mcp }
  template:
    metadata:
      labels: { app: postgres-mcp }
    spec:
      containers:
        - name: server
          image: crystaldba/postgres-mcp   # or "latest"
          args: ["--access-mode=restricted", "--transport=sse"]
          envFrom:
            - secretRef:
                name: postgres-mcp-creds          # holds DATABASE_URI
          ports:
            - containerPort: 8000
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
          livenessProbe:
            httpGet: { path: /sse, port: 8000 }
            periodSeconds: 10
          readinessProbe:
            httpGet: { path: /sse, port: 8000 }
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-mcp
  namespace: kagent
spec:
  selector:
    app: postgres-mcp
  ports:
    - port: 80
      targetPort: 8000
