apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-github
  namespace: kagent
  labels:
    app: mcp-github
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-github
  template:
    metadata:
      labels:
        app: mcp-github
    spec:
      containers:
        - name: mcp-github
          image: ghcr.io/github/github-mcp-server:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: GITHUB_PERSONAL_ACCESS_TOKEN
            value: "test"
          - name: GITHUB_READ_ONLY
            value: "1"
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          # livenessProbe:
          #   httpGet:
          #     path: /sse
          #     port: 8000
          #   initialDelaySeconds: 10
          #   periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-github
  namespace: kagent
spec:
  selector:
    app: mcp-github
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP

